version: "3"

services: 
    web: 
         container_name: exampleappJooycar
         restart: always
         build: .
         ports: 
             - "5000:3000"
         links:
             - mongo
    mongo:
         container_name: mymongodatabaseMarco
         image: mongo
         ports: 
             - "27018:27017"
         logging:
             driver: none

